import { collectDocumentMediaRefs } from '@/lib/media/document-media-refs';
import { resolveAudioBlob } from '@/lib/media/resolve-audio-bytes';
import {
  getPersistenceRequestHeaders,
  isBrowserPersistenceEnabled,
} from '@/lib/persistence/bootstrap';

/**
 * One-time browser → server media backfill for a course (dev/self-host flow).
 *
 * Why: the browser asset pool is IndexedDB-local, so the server-side store (and
 * therefore the course-git repo snapshot) never sees most of a course's media —
 * TTS narration generated before a binding existed, images under a legacy
 * origin, and so on. This walks every media ref the persisted document
 * references, resolves each against the browser pools (asset pool first,
 * `audioFiles` mirror second — the same resolution the player uses), and PUTs
 * the bytes into the server asset store. Idempotent: refs the server already
 * has are skipped via a HEAD-style GET.
 *
 * Server-side afterwards, the ordinary outbound git commit copies `assets/*`
 * into the repo snapshot (git-sync-assets.ts) — so the repo becomes a FULL
 * portable course: document + narration + images/video bytes.
 *
 * Not exported data ("export" means copyright): the bytes are the user's own
 * course media moving between that user's browser and that user's server.
 */

export interface BackfillProgress {
  totalRefs: number;
  uploaded: number;
  skippedExisting: number;
  noBytes: number;
  failed: number;
  lastRef: string;
}

async function fetchExistingServerside(ref: string, headers: Record<string, string>): Promise<boolean> {
  try {
    const response = await fetch(
      `/api/persistence/assets/${encodeURIComponent(ref)}`,
      { headers, method: 'GET' },
    );
    return response.ok;
  } catch {
    return false;
  }
}

async function uploadRef(
  ref: string,
  bytes: Blob,
  headers: Record<string, string>,
): Promise<boolean> {
  const response = await fetch(`/api/persistence/assets/${encodeURIComponent(ref)}`, {
    method: 'PUT',
    headers: {
      ...headers,
      'content-type': bytes.type || 'application/octet-stream',
    },
    body: bytes,
  });
  return response.status === 204 || response.status === 200;
}

export async function backfillCourseMedia(
  document: unknown,
  onProgress?: (progress: BackfillProgress) => void,
): Promise<BackfillProgress> {
  if (!isBrowserPersistenceEnabled()) {
    throw new Error('browser persistence is not enabled (NEXT_PUBLIC_PERSISTENCE)');
  }
  const headers = await getPersistenceRequestHeaders();
  const refs = collectDocumentMediaRefs(document);
  const progress: BackfillProgress = {
    totalRefs: refs.length,
    uploaded: 0,
    skippedExisting: 0,
    noBytes: 0,
    failed: 0,
    lastRef: '',
  };
  onProgress?.({ ...progress });

  const CONCURRENCY = 8;
  let cursor = 0;
  const worker = async () => {
    while (cursor < refs.length) {
      const ref = refs[cursor++];
      if (!ref) break;
      progress.lastRef = ref;
      if (await fetchExistingServerside(ref, headers)) {
        progress.skippedExisting += 1;
        onProgress?.({ ...progress });
        continue;
      }
      let bytes: Blob | null = null;
      try {
        if (/^tts_/.test(ref) || audioIdShape(ref)) {
          bytes = await resolveAudioBlob(ref);
        } else {
          bytes = await poolBytes(ref);
        }
      } catch {
        bytes = null;
      }
      if (!bytes || bytes.size === 0) {
        progress.noBytes += 1;
        onProgress?.({ ...progress });
        continue;
      }
      try {
        if (await uploadRef(ref, bytes, headers)) {
          progress.uploaded += 1;
        } else {
          progress.failed += 1;
        }
      } catch {
        progress.failed += 1;
      }
      onProgress?.({ ...progress });
    }
  };
  await Promise.all(Array.from({ length: CONCURRENCY }, () => worker()));
  return progress;
}

/** Narration ids generated by the app's TTS pipeline (stable prefix forms). */
function audioIdShape(ref: string): boolean {
  return /^(tts_|audio_|speech_)/.test(ref);
}

async function poolBytes(ref: string): Promise<Blob | null> {
  // URL leasing goes through the shared owner (asset-url boundary rule); this
  // module only reads bytes, it never pins URLs itself.
  const { withAssetUrl } = await import('@/lib/media/use-asset-url');
  try {
    return await withAssetUrl(ref, async (url) => {
      if (!url) return null;
      const response = await fetch(url);
      if (!response.ok) return null;
      const blob = await response.blob();
      return blob.size > 0 ? blob : null;
    });
  } catch {
    return null;
  }
}
