import { db } from '@/lib/utils/database';
import { createLogger } from '@/lib/logger';
import { isConcreteMediaAddress } from './resolve-media-ref';
import { mayNameAPoolAsset } from './media-placeholder';
import { withAssetUrl } from './use-asset-url';
import { fetchMediaUrl } from './fetch-media-url';

const COMPATIBILITY_AUDIO_FETCH_TIMEOUT_MS = 15_000;

const log = createLogger('AudioBytes');

/**
 * Bytes an audio reference currently resolves to.
 *
 * A stable-id regeneration commits the replaced narration to the pool first and
 * deliberately keeps the same id; if the `audioFiles` mirror write then fails
 * (quota pressure, a transient IndexedDB error) the row is stale while the pool
 * is current. Every consumer of allocated audio therefore resolves through this
 * one function, with Dexie kept as the fallback for legacy and imported rows
 * that were never pool-backed. A compatibility row whose local bytes were
 * evicted can still carry a CDN `ossKey`; fetch that final source so playback
 * and every export surface agree that the narration exists.
 */
export async function resolveAudioBlob(audioId: string): Promise<Blob | null> {
  const pooled = await pooledAudioBlob(audioId);
  if (pooled) return pooled;
  const record = await db.audioFiles.get(audioId);
  const bytes = record?.blob;
  // Zero-byte rows (evicted, or an empty fetch) are not playable narration:
  // report no bytes so callers keep the reference retryable instead of
  // playing silence.
  if (bytes && bytes.size > 0) return bytes;
  if (record?.ossKey) {
    try {
      const response = await fetchMediaUrl(record.ossKey, COMPATIBILITY_AUDIO_FETCH_TIMEOUT_MS);
      if (response.ok) {
        const fetched = await response.blob();
        // Zero-byte responses are not playable narration. Keep the reference
        // retryable instead of turning an empty CDN response into silence.
        if (fetched.size > 0) return fetched;
      }
    } catch {
      // fall through to the server asset store
    }
  }
  // SERVER FALLBACK (cross-device/cross-tab single source of truth): with
  // server persistence configured, the library also carries narration bytes
  // (uploaded at generation time or by a backfill). A local miss is not
  // "dead" — hydrate from the server, return the bytes; the local mirror is
  // seeded inside the fetch helper (quota-tolerant, failure non-fatal).
  const fetched = await fetchServerAudioBlob(audioId);
  return fetched ?? null;
}

const inFlightServerLookup = new Map<string, Promise<Blob | null>>();

/**
 * Short-lived "missing server-side" cache. The existence probes repeat every
 * status pass; without this every pass re-issues the same 404 for the same
 * ref (hundreds of refs × countless passes = a ~10k-line 404 storm in the dev
 * log). 30s only: freshly regenerated bytes first land in the pool/mirror,
 * which this cache never covers, so a regen stays visible immediately.
 */
const SERVER_MISS_TTL_MS = 30_000;
const serverMissUntil = new Map<string, number>();

/** Auth failures are configuration, not absence — silently folding them into
 * the 30s miss cache makes a credentials regression present exactly like
 * missing narration. Warn rate-limited (one per minute) so the signal exists
 * without a per-ref storm. */
let lastAuthWarnAt = 0;
function warnUnauthorized(status: number): void {
  const now = Date.now();
  if (now - lastAuthWarnAt < 60_000) return;
  lastAuthWarnAt = now;
  log.warn(
    `Narration byte fetch unauthorized (HTTP ${status}); persistence credentials are missing or stale`,
  );
}

function knownMissing(audioId: string): boolean {
  const until = serverMissUntil.get(audioId);
  if (until === undefined) return false;
  if (until <= Date.now()) {
    serverMissUntil.delete(audioId);
    return false;
  }
  return true;
}

async function fetchServerAudioBlob(audioId: string): Promise<Blob | null> {
  if (!audioId || isConcreteMediaAddress(audioId)) return null;
  // Only ids in narration/asset ref shapes ever exist in the server asset
  // store; element-local ids (chart_x, text_y) are not addresses and probing
  // them is pure 404 noise.
  if (!/^(tts_|audio_|speech_|ast_|gen_img_|gen_vid_)/.test(audioId) && !/:/.test(audioId)) {
    return null;
  }
  if (knownMissing(audioId)) return null;
  const pending = inFlightServerLookup.get(audioId);
  if (pending) return pending;
  const promise = (async () => {
    try {
      const { isBrowserPersistenceEnabled, getPersistenceRequestHeaders } = await import(
        '@/lib/persistence/bootstrap'
      );
      if (!isBrowserPersistenceEnabled()) return null;
      const headers = await getPersistenceRequestHeaders();
      const response = await fetch(`/api/persistence/assets/${encodeURIComponent(audioId)}`, {
        headers,
      });
      if (!response.ok) {
        if (response.status === 401 || response.status === 403) warnUnauthorized(response.status);
        serverMissUntil.set(audioId, Date.now() + SERVER_MISS_TTL_MS);
        return null;
      }
      const blob = await response.blob();
      if (!blob || blob.size === 0) return null;
      // Seed the local mirror: future plays resolve locally (quota pressure
      // tolerant — a failed mirror write falls back to per-play server fetch,
      // which the next call re-hydrates).
      const mime = response.headers.get('content-type') || blob.type;
      const seeded: Blob = mime ? blob : blob;
      try {
        await db.audioFiles.put({
          id: audioId,
          stageId: undefined,
          blob: seeded,
          duration: undefined,
          format: mime.replace('audio/', '') || 'wav',
          text: '',
          voice: '',
          createdAt: Date.now(),
        });
      } catch {
        // Quota/full mirror is non-fatal: bytes were returned to the caller.
      }
      return seeded;
    } catch {
      return null;
    } finally {
      inFlightServerLookup.delete(audioId);
    }
  })();
  inFlightServerLookup.set(audioId, promise);
  return promise;
}

/** Resolve several ids at once, preserving input order. */
export async function resolveAudioBlobs(
  audioIds: readonly string[],
): Promise<ReadonlyArray<Blob | null>> {
  return Promise.all(audioIds.map((audioId) => resolveAudioBlob(audioId)));
}

async function pooledAudioBlob(audioId: string): Promise<Blob | null> {
  // A derived narration key predates allocated identities: its bytes are in the
  // local table, never in the pool, so leasing it is a guaranteed miss.
  if (!audioId || isConcreteMediaAddress(audioId) || !mayNameAPoolAsset(audioId)) return null;
  try {
    return await withAssetUrl(audioId, async (url) => {
      if (!url) return null;
      const response = await fetch(url);
      const blob = response.ok ? await response.blob() : null;
      return blob && blob.size > 0 ? blob : null;
    });
  } catch {
    // Stored rows stay the fallback when the pool is unavailable.
    return null;
  }
}
